site_name: Tim Conrad's Blog
theme:
  name: material
  features:
    - navigation.instant
    - toc.follow
    - navigation.tracking
  palette:
    primary: black
    accent: red
plugins:
  - search
  - tags
  - glightbox

markdown_extensions:
  - abbr

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Tim-Conrad

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
